In [48]:
import pandas as pd
df=pd.read_csv(r"D:\AlgoT\brokrage\finalbalance.csv")

In [49]:
df['Date']= pd.to_datetime(df['Date'])

In [50]:
# Ensure the 'Datetime' column is parsed correctly and converted to UTC
df['Datetime'] = pd.to_datetime(df['Date'], utc=True)



df['day'] = df['Date'].dt.day_name()

In [51]:
df['day'] = pd.to_datetime(df['Datetime']).dt.day_name()

In [52]:
# create a new column for date 
df['date'] = pd.to_datetime(df['Date']).dt.date

In [54]:
initial = 100000

In [55]:
# group by date and sum the totalPL
daily_returns = df.groupby('date')['CumReturns'].sum().reset_index()

In [56]:
daily_returns.head(50)

          date  CumReturns
0   2019-01-01         0.0
1   2019-01-02         0.0
2   2019-01-03         0.0
3   2019-01-04         0.0
4   2019-01-07         0.0
5   2019-01-08         0.0
6   2019-01-09         0.0
7   2019-01-10         0.0
8   2019-01-11         0.0
9   2019-01-14         0.0
10  2019-01-15         0.0
11  2019-01-16         0.0
12  2019-01-17         0.0
13  2019-01-18         0.0
14  2019-01-21         0.0
15  2019-01-22         0.0
16  2019-01-23         0.0
17  2019-01-24         0.0
18  2019-01-25     -1062.5
19  2019-01-28       677.5
20  2019-01-29      1310.0
21  2019-01-30     -2355.0
22  2019-01-31     -2627.5
23  2019-02-01         0.0
24  2019-02-04         0.0
25  2019-02-05         0.0
26  2019-02-06         0.0
27  2019-02-07         0.0
28  2019-02-08         0.0
29  2019-02-11      1217.5
30  2019-02-12       722.5
31  2019-02-13      -312.5
32  2019-02-14      2220.0
33  2019-02-15       550.0
34  2019-02-18      2127.5
35  2019-02-19     -1082.5
36  2019-02-20       917.5
37  2019-02-21       667.5
38  2019-02-22       190.0
39  2019-02-25      1015.0
40  2019-02-26     -2470.0
41  2019-02-27      -687.5
42  2019-02-28     -1410.0
43  2019-03-01      1925.0
44  2019-03-05     -2607.5
45  2019-03-06      1687.5
46  2019-03-07      2335.0
47  2019-03-08       352.5
48  2019-03-11       647.5
49  2019-03-12       480.0

In [57]:
daily_returns['balance'] = initial + daily_returns['CumReturns'].cumsum()

In [58]:
daily_returns['totalPLcumsum'] = daily_returns['CumReturns'].cumsum()

In [59]:
#create pct_change column
daily_returns['pct_change'] = daily_returns['balance'].pct_change()

In [60]:
daily_returns

            date  CumReturns   balance  totalPLcumsum  pct_change
0     2019-01-01         0.0  100000.0            0.0         NaN
1     2019-01-02         0.0  100000.0            0.0    0.000000
2     2019-01-03         0.0  100000.0            0.0    0.000000
3     2019-01-04         0.0  100000.0            0.0    0.000000
4     2019-01-07         0.0  100000.0            0.0    0.000000
...          ...         ...       ...            ...         ...
1228  2023-12-22      1930.0  841345.0       741345.0    0.002299
1229  2023-12-26        65.0  841410.0       741410.0    0.000077
1230  2023-12-27     -1102.5  840307.5       740307.5   -0.001310
1231  2023-12-28      2322.5  842630.0       742630.0    0.002764
1232  2023-12-29      -640.0  841990.0       741990.0   -0.000760

[1233 rows x 5 columns]

In [66]:
# Assuming daily_returns is your DataFrame
daily_returns['date'] = pd.to_datetime(daily_returns['date'])

# Now you can use the .dt accessor
daily_returns['date'] = daily_returns['date'].dt.to_pydatetime()

KeyError: 'date'

In [15]:
daily_returns['day'] = daily_returns['date'].dt.day_name()

In [64]:
daily_returns['Date']=daily_returns['date']

In [65]:
daily_returns.set_index('date', inplace=True)

In [21]:
if not pd.api.types.is_datetime64_any_dtype(daily_returns.index):
    daily_returns.index = pd.to_datetime(daily_returns.index)

# Ensure that 'pct_change' column is in float format
daily_returns['pct_change'] = daily_returns['pct_change'].astype(float)

In [37]:
daily_returns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1233 entries, 0 to 1232
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1233 non-null   datetime64[ns]
 1   CumReturns     1233 non-null   float64
 2   balance        1233 non-null   float64
 3   totalPLcumsum  1233 non-null   float64
 4   pct_change     1232 non-null   float64
dtypes: datetime64[ns](1), float64(4)
memory usage: 48.3 KB

In [45]:
daily_returns.dtypes

date             datetime64[ns]
CumReturns              float64
balance                 float64
totalPLcumsum           float64
pct_change              float64
dtype: object

In [46]:
daily_returns.index

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-07', '2019-01-08', '2019-01-09', '2019-01-10',
               '2019-01-11', '2019-01-14',
               ...
               '2023-12-15', '2023-12-18', '2023-12-19', '2023-12-20',
               '2023-12-21', '2023-12-22', '2023-12-26', '2023-12-27',
               '2023-12-28', '2023-12-29'],
              dtype='datetime64[ns]', name='Date', length=1233, freq=None)

In [67]:
import pyfolio as pf
pf.create_full_tear_sheet(returns=daily_returns['pct_change'], benchmark_rets=None)

d:\AlgoT\myenv\lib\site-packages\pyfolio\timeseries.py:724: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  stats = pd.Series()
d:\AlgoT\myenv\lib\site-packages\pyfolio\plotting.py:648: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for stat, value in perf_stats[column].iteritems():

AttributeError: 'numpy.int64' object has no attribute 'to_pydatetime'